### ISSUE TITLE
[Question] WIFI goes out

### ISSUE THREAD

**Issue by StupidVHDLcoder** [Qengineering/YoloCam#2]
I apologize if this is not the correct place to do this, but I am curious what happens if the wifi goes out, does the code for this automatically try to reconnect to the server and display a livestream again if you are trying to setup a 24/7 livestream out in a field to record bees.

**Comment by Qengineering** [comment]
It is the other way around. YoloCam acts like a passive RSTP streamer. 
In other words, your browser tries to connect to YoloCam. If the stream breaks down, your browser freezes first and will come with some connection error. Once the connection is reestablished, refresh your browser content with <F5>. Streaming will continue. 
On the other hand, with a broken internet connection, emails and event recordings are lost. They will not be saved.

**Comment by StupidVHDLcoder** [comment]
Ok! I really appreciate you getting back to me so quickly. I am currently working on a project of my own that involves livestreaming out in a field as I mentioned before. My goal is to setup an OV5647 5MP B003504 with a raspberry pi 3 and have it livestream 24/7 and be able to reconnect if it loses power and turns back on, or try to be reconnecting if it cannot connect to wifi. Thankfully I am getting closer to having a working script.
